slv = input('Введите слово с гласными буквами: ')
egls=slv.count('e')
agls=slv.count('a')
igls=slv.count('i')
ugls=slv.count('u')
ogls=slv.count('o')
sgls=egls+agls+igls+ugls+ogls
print("всего гласных",sgls)
print("всего согласных",len(slv)-sgls)
if (egls==0): print ("гласной e в слове False")
else:   print("e=",egls)
if (ugls==0): print ("гласной u в слове False")
else:   print("u=",ugls)
if (ogls==0): print ("гласной o в слове False")
else:   print("o=",ogls)
if (agls==0): print ("гласной a в слове False")
else:   print("a=",agls)
if (igls==0): print ("гласной i в слове False")
else:   print("i=",igls)